# -*- coding: utf-8 -*-
"""CatOrCow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhXjbNpJAZGL1rf-IKLRqCSM0MvqijwI
"""

!pip install Pillow

!pip install tf_keras

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"

from tensorflow.keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

MODEL_PATH = "keras_model.h5"
LABELS_PATH = "labels.txt"
IMAGE_PATH = "test.jpg"
IMG_SIZE = (224, 224)


def load_labels(path):
    with open(path, "r") as f:
        return [line.strip().split(" ", 1)[1] if " " in line else line.strip()
                for line in f.readlines()]


def preprocess_image(image_path):
    image = Image.open(image_path).convert("RGB")
    image = ImageOps.fit(image, IMG_SIZE, Image.Resampling.LANCZOS)
    image_array = np.asarray(image)
    normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1
    data = np.expand_dims(normalized_image_array, axis=0)
    return data


print("Loading model...")
model = load_model(MODEL_PATH, compile=False)
labels = load_labels(LABELS_PATH)

print(f"Processing image: {IMAGE_PATH}")
data = preprocess_image(IMAGE_PATH)

prediction = model.predict(data)
index = np.argmax(prediction)
class_name = labels[index]
confidence = prediction[0][index]

print("\n--- Prediction Result ---")
print(f"Class: {class_name}")
print(f"Confidence: {confidence * 100:.2f}%")